name: build
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test with coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Run tests
        run: go test -v -coverprofile=cover.out ./...
      - name: Send coverage
        run: bash <(curl -s https://codecov.io/bash)
